### ISSUE TITLE
Use JSON format on API calls

### ISSUE THREAD

**Issue by YOUR1** [dapete42/imagemapedit#1]
Using the XML format on api calls causes errors in the api; ie:
<?xml version="1.0"?>
<api>
  <error code="internal_api_error_MWException" info="Exception Caught: Internal error in ApiResult::setElement: Bad parameter" xml:space="preserve" />
</api>

I'm using MW 1.19, but I've seen other wiki's throwing this error.

Solution is to use json as output format, and to be honest, its better and faster then parsing XML.

See fix at pull request #2

**Comment by dapete42** [comment]
Sorry I didn't see this earlier; I had notifications turned off and rarely go to GitHub. After a quick test I've merged your pull request and updated the production version.
